<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Cloud.Configurations.Azure.KeyVault\Core.Cloud.Configurations.Azure.KeyVault.csproj" />
    <ProjectReference Include="..\Core.Extensions.Azure\Core.Extensions.Azure.csproj" />
    <ProjectReference Include="..\Core.Cloud.KeyManagement\Core.Cloud.KeyManagement.csproj" />
  </ItemGroup>

</Project>
