<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks Condition=" '$(TargetFrameworks)' != '' ">net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>b8f320a9-24d0-410e-8057-1e8eb0809dcb</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Core.Hosting.AspNetCore.WebApi\Core.Hosting.AspNetCore.WebApi.csproj" />
    <ProjectReference Include="..\..\src\Core.HttpClient.Authorization\Core.HttpClient.Authorization.csproj" />
    <ProjectReference Include="..\..\src\Core.Logging.AspNetCore.Serilog\Core.Logging.AspNetCore.Serilog.csproj" />
    <ProjectReference Include="..\..\src\Core.OpenTelemetry.AspNetCore\Core.OpenTelemetry.AspNetCore.csproj" />
  </ItemGroup>

</Project>
