<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Core" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Extensions.Hosting\Core.Extensions.Hosting.csproj" />
  </ItemGroup>

</Project>
