name: Nuget-Package
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "release/*"
      - "feature/*"
env:
  Solution: Core.sln
  Configuration: ${{ contains(fromJSON('["refs/head/release/"]'), github.ref) && 'Release' || 'Debug' }}
  VersionSuffix: ${{ contains('refs/head/release', github.ref) && '' || contains('refs/head/main/', github.ref) && format('rc.{0}', github.sha) || format('preview.{0}', github.sha) }}
jobs:
  dotnet-pack:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution }}
      - name: Build
        run: dotnet build ${{ env.Solution }} --configuration ${{ env.Configuration }} --no-restore
      - name: Test
        run: dotnet test ${{ env.Solution }} --configuration ${{ env.Configuration }} --no-restore --no-build
      - name: Pack
        run: dotnet pack ${{ env.Solution }} --configuration ${{ env.Configuration }} --version-suffix ${{ env.VersionSuffix }} --no-restore --no-build -o /packages
      #   - name: Push
      #     run: dotnet nuget push "**/bin/${{ env.Configuration }}/*.nupkg" -k ${{ env.NUGET_AUTH_TOKEN }} --source github
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: core-package
          path: "/packages/*.nupkg" # or path/to/artifact
